In [2]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [3]:
os.getcwd()

'c:\\Users\\pedro_baldini\\OneDrive - YanmarGlobal\\Documentos\\Pos Graduacao\\02_Engenharia_Dados_Pratica\\Desenvolvimento\\myproject\\scripts'

In [5]:
# Criando a conexão com o banco
con = duckdb.connect(database='dados_duck.db', read_only=False)

In [19]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2025-12-29 15:08:26.041117
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2025-12-29 15:08:26.041117
2  10003    PREGO  BT10    100     60  z0019_2.csv 2025-12-29 15:08:26.041117

In [20]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP
            )
""")

In [21]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [25]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-12-29 15:03:25.385208
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-12-29 15:03:25.385208
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-12-29 15:03:25.385208
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-12-29 15:08:26.041117
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-12-29 15:08:26.041117
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-12-29 15:08:26.041117

In [24]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [26]:
con.close()